spring:
  application:
    name: bouquetomat
  datasource:
    url: jdbc:mysql://localhost:3306/bouquetomat
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
